name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.0.x'
    - name: Test
      run: dotnet test tests/tests.csproj --collect:"XPlat Code Coverage"
    - name: Upload coverage files
      env:
        CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l CSharp $(find . -name 'coverage.cobertura.xml' -printf '-r %p ')
