# This workflow compiles and publishes AOT version for x64 Linux
name: .NET Core AOT Linux

on:
  push:
     tags:
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags
      - v0.9.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Add current ISO time to env property
      run: echo "CURRENT_TIME=`date -Iseconds`" >> $GITHUB_ENV
    - name: Publish
      run: |
        cd clitool
        dotnet publish -o out --configuration Release -r linux-x64 /p:AssemblyName=audalf-cli /p:InformationalVersion="Build time: ${{env.CURRENT_TIME}} Short hash: ${{env.SHORT_SHA}}"
    - name: Install zip
      run: sudo apt install zip
    - name: Package Linux-x64 release
      run: zip -9 release_${{ github.ref_name }}-linux_x64.zip clitool/out
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release_${{ github.ref_name }}-linux_x64.zip
